[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_flags =
    --before=default_reset
    --after=hard_reset
    --no-stub
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
